# Generated by Django 4.1.3 on 2022-11-20 20:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scholarship",
            name="active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="scholarship",
            name="constraint_agpa",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(10.0),
                ],
                verbose_name="Aggregated GPA",
            ),
        ),
        migrations.AddField(
            model_name="scholarship",
            name="constraint_annual_income",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
