# Generated by Django 4.1.3 on 2022-11-23 16:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_mcmapp_delete_mcmapplication"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("title", models.TextField()),
                ("content", models.TextField(blank=True, null=True)),
                ("attachment", models.FileField(blank=True, null=True, upload_to="")),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("enabled", models.BooleanField(default=True)),
            ],
        ),
    ]
