# Generated by Django 4.1.3 on 2022-11-20 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_scholarship_active_scholarship_constraint_agpa_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scholarship",
            name="constraint_agpa",
        ),
        migrations.RemoveField(
            model_name="scholarship",
            name="constraint_annual_income",
        ),
        migrations.RemoveField(
            model_name="scholarship",
            name="constraint_cgpa",
        ),
        migrations.RemoveField(
            model_name="scholarship",
            name="constraint_class10_percentage",
        ),
        migrations.RemoveField(
            model_name="scholarship",
            name="constraint_class12_percentage",
        ),
    ]
