# Generated by Django 4.1.3 on 2022-11-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_mcmapplication_alter_scholarshipcategory_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mcmapplication",
            name="income_certificate",
            field=models.FileField(
                default=None,
                help_text="Please upload a digital / scanned copy of your income certificate",
                upload_to="",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mcmapplication",
            name="supporting_documents",
            field=models.FileField(
                blank=True,
                help_text="Please upload supporting documents in a .zip format, if any",
                null=True,
                upload_to="",
            ),
        ),
    ]
