# Generated by Django 4.1.3 on 2022-11-23 16:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_notice"),
    ]

    operations = [
        migrations.CreateModel(
            name="NoticeCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("title", models.TextField()),
                ("collapsed", models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name="notice",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="website.noticecategory",
            ),
        ),
    ]
