# Generated by Django 4.1.3 on 2022-11-28 16:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_mcmapplication_income_certificate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mcmapplication",
            name="class_12_marks",
            field=models.CharField(
                help_text="Enter percentage e.g. 89.8 ", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="mcmapplication",
            name="income_certificate",
            field=models.FileField(
                help_text="Please upload a digital / scanned copy of your income certificate",
                upload_to="income_certificates",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpg", "png", "jpeg"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="mcmapplication",
            name="mcp_special_reason",
            field=models.TextField(
                blank=True,
                help_text="SPECIFIC REASON FOR APPLYING MCM SPECIAL?",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="mcmapplication",
            name="other_scholarship_details",
            field=models.TextField(
                blank=True, help_text="DETAILS OF OTHER SCHOLARSHIP APPLIED", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mcmapplication",
            name="previous_year_scholarship_amount",
            field=models.IntegerField(
                blank=True, help_text="AMOUNT OF THE PREVIOUS SCHOLARSHIP", null=True
            ),
        ),
        migrations.AlterField(
            model_name="mcmapplication",
            name="previous_year_scholarship_details",
            field=models.TextField(
                blank=True,
                help_text="DETAILS OF PREVIOUS SCHOLARSHIP RECEIVED",
                null=True,
            ),
        ),
    ]
