# Generated by Django 4.1.3 on 2022-11-21 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_remove_scholarship_constraint_agpa_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Constraint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ScholarshipConstraint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filter_using_min", models.BooleanField(default=False)),
                ("filter_using_max", models.BooleanField(default=False)),
                ("min_value", models.FloatField()),
                ("max_value", models.FloatField()),
                (
                    "constraint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.constraint",
                    ),
                ),
                (
                    "scholarship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.scholarship",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="scholarship",
            name="constraints",
            field=models.ManyToManyField(
                through="website.ScholarshipConstraint", to="website.constraint"
            ),
        ),
    ]
