# Generated by Django 4.1.3 on 2022-11-23 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0004_noticecategory_notice_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="noticecategory",
            options={"verbose_name_plural": "Notice Categories"},
        ),
        migrations.RemoveField(
            model_name="notice",
            name="enabled",
        ),
    ]
