# Generated by Django 4.1.3 on 2022-11-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0004_alter_mcmapplication_class_12_marks_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mcmapplication",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mcmapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("APPROVED", "APPROVED"),
                    ("REJECTED", "REJECTED"),
                ],
                default="PENDING",
                max_length=1024,
            ),
        ),
    ]
