# Generated by Django 4.1.3 on 2022-11-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0004_constraint_scholarshipconstraint_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scholarshipconstraint",
            name="filter_using_max",
        ),
        migrations.RemoveField(
            model_name="scholarshipconstraint",
            name="filter_using_min",
        ),
        migrations.AlterField(
            model_name="scholarshipconstraint",
            name="max_value",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="scholarshipconstraint",
            name="min_value",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
