# Generated by Django 4.1.3 on 2022-11-23 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0005_alter_noticecategory_options_remove_notice_enabled"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notice",
            name="content",
        ),
    ]
