# Generated by Django 4.1.3 on 2022-11-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0005_remove_scholarshipconstraint_filter_using_max_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scholarship",
            name="active",
        ),
        migrations.AddField(
            model_name="scholarship",
            name="amount",
            field=models.CharField(default="tF", max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="scholarship",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
    ]
