# Generated by Django 4.1.3 on 2022-11-28 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0003_student_adm_mode_student_app_no_student_branch_code_and_more",
        ),
        ("website", "0006_grievance"),
    ]

    operations = [
        migrations.AddField(
            model_name="grievance",
            name="student",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.student",
            ),
            preserve_default=False,
        ),
    ]
