# Generated by Django 4.1.3 on 2022-11-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0007_grievance_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="grievance",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
    ]
