# Generated by Django 4.1.3 on 2022-11-29 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0008_grievance_remarks"),
    ]

    operations = [
        migrations.AddField(
            model_name="constraint",
            name="required",
            field=models.BooleanField(default=True),
        ),
    ]
