# Generated by Django 4.1.3 on 2022-11-29 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0010_studentdata"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StudentData",
        ),
    ]
