# Generated by Django 4.1.3 on 2022-12-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0011_delete_studentdata"),
    ]

    operations = [
        migrations.AddField(
            model_name="notice",
            name="link",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="mcmapplication",
            name="supporting_documents",
            field=models.FileField(
                blank=True,
                help_text="Please upload supporting documents in a .zip format, if any",
                null=True,
                upload_to="supporting_documents",
            ),
        ),
        migrations.AlterField(
            model_name="notice",
            name="attachment",
            field=models.FileField(
                blank=True, null=True, upload_to="notice_attachments"
            ),
        ),
    ]
