# Generated by Django 4.1.3 on 2022-12-03 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_session_remove_student_cat_type_and_more"),
        ("website", "0013_rename_mcmapplication_mcmtietapplication_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReceivedScholarship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year_of_study",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                ("branch", models.CharField(blank=True, max_length=1024, null=True)),
                ("programme", models.CharField(blank=True, max_length=1024, null=True)),
                ("current_cgpa", models.FloatField(blank=True, null=True)),
                ("cgpa_1st_semester", models.FloatField(blank=True, null=True)),
                ("cgpa_2nd_semester", models.FloatField(blank=True, null=True)),
                ("cgpa_3rd_semester", models.FloatField(blank=True, null=True)),
                ("sgpa_5th_semester", models.FloatField(blank=True, null=True)),
                ("sgpa_6th_semester", models.FloatField(blank=True, null=True)),
                ("agpa", models.FloatField(blank=True, null=True)),
                ("marks", models.FloatField(blank=True, null=True)),
                ("jee_rank", models.FloatField(blank=True, null=True)),
                ("pcme_percentage", models.FloatField(blank=True, null=True)),
                ("pcb_percentage", models.FloatField(blank=True, null=True)),
                ("ti_rank", models.FloatField(blank=True, null=True)),
                ("tu_rank", models.FloatField(blank=True, null=True)),
                (
                    "twelfth_overall_percentage",
                    models.FloatField(blank=True, null=True),
                ),
                ("amount", models.PositiveIntegerField()),
                (
                    "scholarship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.scholarship",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.session",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.student",
                    ),
                ),
            ],
        ),
    ]
