# Generated by Django 4.1.3 on 2022-12-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0014_receivedscholarship"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receivedscholarship",
            name="branch",
            field=models.CharField(default="UNSPECIFIED", max_length=1024),
        ),
    ]
