# Generated by Django 4.1.3 on 2022-12-04 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_remove_student_adm_mode_remove_student_eng_and_more"),
        ("website", "0015_alter_receivedscholarship_branch"),
    ]

    operations = [
        migrations.CreateModel(
            name="MCMOtherApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "declaration",
                    models.BooleanField(
                        help_text="I acknowledge that I have read all the eligibility criteria of this scholarship and I am eligible for applying to this scholarship."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("APPROVED", "APPROVED"),
                            ("REJECTED", "REJECTED"),
                        ],
                        default="PENDING",
                        max_length=1024,
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "scholarship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.scholarship",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Merit cum Means Other Application",
                "verbose_name_plural": "Merit cum Means Other Applications",
            },
        ),
        migrations.CreateModel(
            name="MCMAlumniApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "declaration",
                    models.BooleanField(
                        help_text="I acknowledge that I have read all the eligibility criteria of this scholarship and I am eligible for applying to this scholarship."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("APPROVED", "APPROVED"),
                            ("REJECTED", "REJECTED"),
                        ],
                        default="PENDING",
                        max_length=1024,
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "scholarship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.scholarship",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Merit cum Means Alumni Application",
                "verbose_name_plural": "Merit cum Means Alumni Applications",
            },
        ),
    ]
