# Generated by Django 4.1.3 on 2022-12-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0017_mcmotherapplication_bank_account_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mcmotherapplication",
            name="photograph",
            field=models.FileField(
                blank=True,
                help_text="Passport size photograph in JPG/PNG under 2 MB.",
                null=True,
                upload_to="photographs",
            ),
        ),
    ]
