# Generated by Django 4.1.3 on 2022-12-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0018_mcmotherapplication_photograph"),
    ]

    operations = [
        migrations.AddField(
            model_name="mcmalumniapplication",
            name="bank_account_number",
            field=models.CharField(
                default="", help_text="Bank Savings Account Number", max_length=255
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mcmalumniapplication",
            name="bank_ifsc_code",
            field=models.CharField(
                default="", help_text="Bank IFSC Code", max_length=255
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mcmalumniapplication",
            name="bank_name",
            field=models.CharField(
                default="", help_text="Bank Branch Address", max_length=255
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mcmalumniapplication",
            name="branch",
            field=models.CharField(default="", help_text="Branch", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mcmalumniapplication",
            name="current_cgpa",
            field=models.CharField(
                default="", help_text="Current CGPA", max_length=255
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mcmalumniapplication",
            name="family_income_per_annum",
            field=models.CharField(
                default="", help_text="Family income per annum", max_length=255
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mcmalumniapplication",
            name="father_contact_number",
            field=models.PositiveIntegerField(
                default=0, help_text="Father's Contact Number"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mcmalumniapplication",
            name="father_name",
            field=models.CharField(
                default="", help_text="Father's Name", max_length=255
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mcmalumniapplication",
            name="father_profession",
            field=models.CharField(
                default="", help_text="Father's Profession", max_length=255
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mcmalumniapplication",
            name="jee_main_rank",
            field=models.CharField(
                default="", help_text="JEE Main Rank", max_length=255
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mcmalumniapplication",
            name="mother_contact_number",
            field=models.PositiveIntegerField(
                default=0, help_text="Mother's Contact Number"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mcmalumniapplication",
            name="mother_name",
            field=models.CharField(
                default="", help_text="Mother's Name", max_length=255
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mcmalumniapplication",
            name="mother_profession",
            field=models.CharField(
                default="", help_text="Mother's Profession", max_length=255
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mcmalumniapplication",
            name="personal_contact_number",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mcmalumniapplication",
            name="photograph",
            field=models.FileField(
                blank=True,
                help_text="Passport size photograph in JPG/PNG under 2 MB.",
                null=True,
                upload_to="photographs",
            ),
        ),
        migrations.AddField(
            model_name="mcmalumniapplication",
            name="roll_no",
            field=models.CharField(
                default="", help_text="Registration/Roll No", max_length=20
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mcmalumniapplication",
            name="year",
            field=models.CharField(default="", help_text="Year", max_length=20),
            preserve_default=False,
        ),
    ]
