# Generated by Django 4.1.3 on 2022-12-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0019_mcmalumniapplication_bank_account_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mcmalumniapplication",
            name="banK_address",
            field=models.CharField(
                default="", help_text="Bank Branch Address", max_length=255
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mcmotherapplication",
            name="banK_address",
            field=models.CharField(
                default="", help_text="Bank Branch Address", max_length=255
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="mcmalumniapplication",
            name="bank_name",
            field=models.CharField(help_text="Student's Bank Name", max_length=255),
        ),
        migrations.AlterField(
            model_name="mcmotherapplication",
            name="bank_name",
            field=models.CharField(help_text="Student's Bank Name", max_length=255),
        ),
    ]
