# Generated by Django 4.1.3 on 2022-12-05 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0021_certificaterequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificaterequest",
            name="date_requested",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
