# Generated by Django 4.1.3 on 2022-12-05 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0022_certificaterequest_date_requested"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificaterequest",
            name="date_approved",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="certificaterequest",
            name="year_of_passing",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
