# Generated by Django 4.1.3 on 2022-12-05 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0024_alter_certificaterequest_received_scholarship"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificaterequest",
            name="certificate",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
