# Generated by Django 4.1.3 on 2022-12-05 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0025_certificaterequest_certificate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificaterequest",
            name="date_approved",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="certificaterequest",
            name="year_of_passing",
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
