# Generated by Django 4.1.3 on 2022-11-23 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="batch",
        ),
        migrations.RemoveField(
            model_name="student",
            name="branch",
        ),
        migrations.RemoveField(
            model_name="student",
            name="roll_no",
        ),
        migrations.DeleteModel(
            name="Batch",
        ),
        migrations.DeleteModel(
            name="Branch",
        ),
    ]
