# Generated by Django 4.1.3 on 2022-11-20 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="batch",
            options={"verbose_name_plural": "Batches"},
        ),
    ]
