# Generated by Django 4.1.3 on 2022-11-21 12:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=1024)),
            ],
            options={
                "verbose_name_plural": "Branches",
            },
        ),
        migrations.AddField(
            model_name="student",
            name="branch",
            field=models.ForeignKey(
                default="COE",
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.branch",
            ),
            preserve_default=False,
        ),
    ]
