# Generated by Django 4.1.3 on 2022-11-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_student_batch_remove_student_branch_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="adm_mode",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="app_no",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="branch_code",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="branch_desc",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="cat_type",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="dob",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="eng",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="father_name",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="jee_rank",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="mother_name",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="pcm",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="pcm_total",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="pcme",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="pcme_percentage",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="program_name",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="programme",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="roll_no",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="sex",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="student_name",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
