# Generated by Django 4.1.3 on 2022-11-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0003_student_adm_mode_student_app_no_student_branch_code_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("excel_file", models.FileField(upload_to="excel_files")),
                ("archived", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Upload Student Data",
            },
        ),
    ]
