# Generated by Django 4.1.3 on 2022-12-02 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_studentdata"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StudentData",
        ),
    ]
