# Generated by Django 4.1.3 on 2022-12-03 09:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_delete_studentdata"),
    ]

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=1024)),
                ("current", models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="student",
            name="cat_type",
        ),
        migrations.RemoveField(
            model_name="student",
            name="pcme_percentage",
        ),
        migrations.AddField(
            model_name="student",
            name="current_session",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.session",
            ),
        ),
    ]
