# Generated by Django 4.1.3 on 2022-12-03 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_session_remove_student_cat_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="adm_mode",
        ),
        migrations.RemoveField(
            model_name="student",
            name="eng",
        ),
        migrations.RemoveField(
            model_name="student",
            name="jee_rank",
        ),
        migrations.RemoveField(
            model_name="student",
            name="pcm",
        ),
        migrations.RemoveField(
            model_name="student",
            name="pcm_total",
        ),
        migrations.RemoveField(
            model_name="student",
            name="pcme",
        ),
    ]
