# Generated by Django 4.1.3 on 2022-12-05 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_remove_student_adm_mode_remove_student_eng_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="current_session",
        ),
        migrations.AlterField(
            model_name="student",
            name="app_no",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="dob",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
